### ISSUE TITLE
Description limits length of annotation data to 5000 characters

### ISSUE THREAD

**Issue by tech234a** [afrmtbl/AnnotationsRestored#2]
YouTube descriptions limit users to 5000 characters, and I tried to place a converted set of annotations in the description, but it was too long. Can we store annotations in the extension storage for testing?

**Comment by tech234a** [comment]
I noticed the new format requires significantly fewer characters than the original one, so that's a step in the right direction. Is any important data lost?

**Comment by afrmtbl** [comment]
> YouTube descriptions limit users to 5000 characters, and I tried to place a converted set of annotations in the description, but it was too long.

Yeah, ideally new annotations would be uploaded to a server just like the older ones, but I don't have access to one. I chose the description instead of, for example, comments because they don't require scrolling to load.

> Can we store annotations in the extension storage for testing?

I'll add a popup when you click the extension's icon that allows you to load either YouTube or converted annotation data.

> I noticed the new format requires significantly fewer characters than the original one, so that's a step in the right direction. Is any important data lost?

I need to look at more annotation data, but the only thing I know of right now that isn't included is appearance data, such as background and foreground colors, background opacity, and text size. I think most of the size savings are from the repetitiveness of the XML tags and reducing super long links that are just time stamps like this: `https://www.youtube.com/watch?annotation_id=annotation_1265285409&amp;ei=R_s7XKT_KsHCigTVw624Ag&amp;feature=iv&amp;src_vid=jqUu0vIh4Ig&amp;v=jqUu0vIh4Ig#t=1m32.6s` to just `as=92`

**Comment by afrmtbl** [comment]
The popup has been added

**Comment by tech234a** [comment]
Nice work on the popup!

**Comment by afrmtbl** [comment]
Addressed with #11 and 465116496bcf463e2ab39d0d0d30c8034a513212
